/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Comparator;
import java.util.ArrayList;
import java.util.Collections;
/*
This program was created by Jesse Jones
on June 16th, 2023
for the purpose of having my own gift app to share with others
*/
public class GifteryUI extends javax.swing.JFrame {
    // Creates global String list
    ArrayList <String[]> userList = new ArrayList();
    ArrayList <String[]> preList = new ArrayList();
    private boolean isAscending = true;
    
    public GifteryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userSortGroup = new javax.swing.ButtonGroup();
        preSortGroup = new javax.swing.ButtonGroup();
        titleBackground = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        giftNameLabel = new javax.swing.JLabel();
        manufacturerLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        giftNameTextField = new javax.swing.JTextField();
        manufacturerTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        userAscendingPrice = new javax.swing.JRadioButton();
        userDescendingPrice = new javax.swing.JRadioButton();
        plusListButton = new javax.swing.JButton();
        outputScroll1 = new javax.swing.JScrollPane();
        outputArea1 = new javax.swing.JTextArea();
        giftListLabel = new javax.swing.JLabel();
        giftListTextField = new javax.swing.JTextField();
        preAscendingPrice = new javax.swing.JRadioButton();
        preDescendingPrice = new javax.swing.JRadioButton();
        showListButton = new javax.swing.JButton();
        outputScroll2 = new javax.swing.JScrollPane();
        outputArea2 = new javax.swing.JTextArea();
        dollarSignLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleBackground.setBackground(new java.awt.Color(78, 120, 78));

        titleLabel.setFont(new java.awt.Font("Avenir", 3, 30)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Giftery");

        javax.swing.GroupLayout titleBackgroundLayout = new javax.swing.GroupLayout(titleBackground);
        titleBackground.setLayout(titleBackgroundLayout);
        titleBackgroundLayout.setHorizontalGroup(
            titleBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBackgroundLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleBackgroundLayout.setVerticalGroup(
            titleBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        giftNameLabel.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        giftNameLabel.setText("Gift Name:");

        manufacturerLabel.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        manufacturerLabel.setText("Manufacturer:");

        priceLabel.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        priceLabel.setText("Price:");

        giftNameTextField.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        manufacturerTextField.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        priceTextField.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        userSortGroup.add(userAscendingPrice);
        userAscendingPrice.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        userAscendingPrice.setText("Ascending Price");

        userSortGroup.add(userDescendingPrice);
        userDescendingPrice.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        userDescendingPrice.setText("Descending Price");

        plusListButton.setBackground(new java.awt.Color(133, 205, 133));
        plusListButton.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        plusListButton.setText("+ List");
        plusListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusListButtonActionPerformed(evt);
            }
        });

        outputArea1.setColumns(20);
        outputArea1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        outputArea1.setRows(5);
        outputScroll1.setViewportView(outputArea1);

        giftListLabel.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        giftListLabel.setText("Gift List:");

        giftListTextField.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        preSortGroup.add(preAscendingPrice);
        preAscendingPrice.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        preAscendingPrice.setText("Ascending Price");

        preSortGroup.add(preDescendingPrice);
        preDescendingPrice.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        preDescendingPrice.setText("Descending Price");

        showListButton.setBackground(new java.awt.Color(133, 205, 133));
        showListButton.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        showListButton.setText("Show List");
        showListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListButtonActionPerformed(evt);
            }
        });

        outputArea2.setColumns(20);
        outputArea2.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        outputArea2.setRows(5);
        outputScroll2.setViewportView(outputArea2);

        dollarSignLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        dollarSignLabel.setText("$");

        exitButton.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 0, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(outputScroll1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(giftNameLabel)
                                                .addComponent(manufacturerLabel))
                                            .addGap(24, 24, 24))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(priceLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dollarSignLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                        .addComponent(manufacturerTextField)
                                        .addComponent(giftNameTextField)))
                                .addComponent(plusListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userAscendingPrice)
                                .addGap(18, 18, 18)
                                .addComponent(userDescendingPrice)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(giftListLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(giftListTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(preAscendingPrice)
                                        .addGap(18, 18, 18)
                                        .addComponent(preDescendingPrice)
                                        .addGap(0, 38, Short.MAX_VALUE))
                                    .addComponent(outputScroll2)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giftNameLabel)
                    .addComponent(giftNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giftListLabel)
                    .addComponent(giftListTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerLabel)
                    .addComponent(preAscendingPrice)
                    .addComponent(preDescendingPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel)
                    .addComponent(showListButton)
                    .addComponent(dollarSignLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userAscendingPrice)
                            .addComponent(userDescendingPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plusListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(outputScroll1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(outputScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusListButtonActionPerformed
        // Clears previous outputs
        outputArea1.setText("");
        outputArea2.setText("");

        // Check for index value out of range
        if (userList.size() > 15) {
            outputArea1.setText("Error! \nIndex value out of range");
            return;
        }
                
        // Number check
        String giftName = giftNameTextField.getText().trim();
        String manufacturer = manufacturerTextField.getText().trim();
        String price = priceTextField.getText().trim();
        
        if (giftName.isEmpty() || manufacturer.isEmpty() || price.isEmpty()) {
            outputArea1.setText("Error! \nNo value has been entered. \nPlease enter a value.");
            return;
        }
    
        // Finds if ascending or desending button is clicked
        if (userAscendingPrice.isSelected()) {
            isAscending = true;
        } else if (userDescendingPrice.isSelected()) {
            isAscending = false;
        } else {
            outputArea1.setText("Error! \nNo sorting option is selected. \nPlease select an option before \nclicking the button.");
            return;
        }
        
        // Catches character and negative number inputs for price
        double priceValue;
        try {
            priceValue = Double.parseDouble(price);
        } catch (NumberFormatException e) {
            outputArea1.setText("Error! \nPrice value not a number. \nPlease enter a correct number value.");
            return;
        }
        if (priceValue < 0 || !Double.isFinite(priceValue)) {
            outputArea1.setText("Error! \nPrice must be a positive number.");
            return;
        }
        
        // Looks for digits in gift name and manufacturer
        if (containsDigits(giftName) || containsDigits(manufacturer)) {
            // Outputs error message
            outputArea1.setText("Error! \nGift name and/or manufacturer value \nis a number. \nPlease input a name \ninstead of numbers");
        
            // Clears input
            giftNameTextField.setText("");
            manufacturerTextField.setText("");
            priceTextField.setText("");
            giftListTextField.setText("");
        } else {
            // Adds values to list and sorts the list
            String[] gift = {giftName, manufacturer, price};
            userList.add(gift);
            Collections.sort(userList, new Comparator<String[]>() {
                @Override
                public int compare(String[] gift1, String[] gift2) {
                    double price1 = Double.parseDouble(gift1[2]);
                    double price2 = Double.parseDouble(gift2[2]);
                    if (isAscending) {
                        return Double.compare(price1, price2);
                    } else {
                        return Double.compare(price2, price1);
                    }
                }
            });

            // Clears output then outputs list
            outputArea1.setText("");
            for (String[] g : userList) {
                outputArea1.append(g[0] + " " + g[1] + " " + g[2] + "\n");
            }
        
            // Writes to the txt file
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter("CreateList.txt"));
            
                for (String[] g : userList) {
                    writer.write(g[0] + ", " + g[1] + ", " + g[2]);
                    writer.newLine();
                }
            
                writer.close();
                outputArea1.append("Array information written to the 'CreateList' file.");
            } catch (IOException e) {
                outputArea1.setText("Error writing to the file: " + e.getMessage());
            }
        
            // Clears input
            giftNameTextField.setText("");
            manufacturerTextField.setText("");
            priceTextField.setText("");
            giftListTextField.setText("");
        }
    }//GEN-LAST:event_plusListButtonActionPerformed

    private void showListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListButtonActionPerformed
        // Clears previous outputs
        outputArea1.setText("");
        outputArea2.setText("");

        // Check for index value out of range
        if (userList.size() > 15) {
            outputArea2.setText("Error! \nIndex value out of range");
            return;
        }
                
        // Number check
        String test = giftListTextField.getText();
        
        /*
        Would be used for the actual program when inputting a link
        if (test.isEmpty()) {
            outputArea2.setText("Error! \nNo value has been entered. \nPlease enter a value.");
            return;
        }
        */
        
        // Finds if ascending or desending button is clicked
        if (preAscendingPrice.isSelected()) {
            isAscending = true;
        } else if (preDescendingPrice.isSelected()) {
            isAscending = false;
        } else {
            outputArea2.setText("Error! \nNo sorting option is selected. \nPlease select an option before \nclicking the button.");
            return;
        }
        
        // Read the file and populate the list
        try (BufferedReader reader = new BufferedReader(new FileReader("Read From List.txt"))) {
            String line;
            preList.clear();

            while ((line = reader.readLine()) != null) {
                String[] gift = line.split(", ");
                preList.add(gift);
            }

            // Sort the list based on the selected sorting order
            Collections.sort(preList, new Comparator<String[]>() {
                @Override
                public int compare(String[] gift1, String[] gift2) {
                    double price1 = Double.parseDouble(gift1[2]);
                    double price2 = Double.parseDouble(gift2[2]);
                    if (isAscending) {
                        return Double.compare(price1, price2);
                    } else {
                        return Double.compare(price2, price1);
                    }
                }
            });

            // Update the output area with the sorted list
            outputArea2.setText("");
            for (String[] gift : preList) {
                outputArea2.append(gift[0] + ", " + gift[1] + ", $" + gift[2] + "\n");
            }
        } catch (IOException e) {
            outputArea2.setText("Error reading from the file: " + e.getMessage());
        }
        
        // Clears input
        giftNameTextField.setText("");
        manufacturerTextField.setText("");
        priceTextField.setText("");
        giftListTextField.setText("");
    }//GEN-LAST:event_showListButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private boolean containsDigits(String input) {
        for (char c : input.toCharArray()) {
            if (Character.isDigit(c)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GifteryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GifteryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GifteryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GifteryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GifteryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dollarSignLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel giftListLabel;
    private javax.swing.JTextField giftListTextField;
    private javax.swing.JLabel giftNameLabel;
    private javax.swing.JTextField giftNameTextField;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JTextField manufacturerTextField;
    private javax.swing.JTextArea outputArea1;
    private javax.swing.JTextArea outputArea2;
    private javax.swing.JScrollPane outputScroll1;
    private javax.swing.JScrollPane outputScroll2;
    private javax.swing.JButton plusListButton;
    private javax.swing.JRadioButton preAscendingPrice;
    private javax.swing.JRadioButton preDescendingPrice;
    private javax.swing.ButtonGroup preSortGroup;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton showListButton;
    private javax.swing.JPanel titleBackground;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JRadioButton userAscendingPrice;
    private javax.swing.JRadioButton userDescendingPrice;
    private javax.swing.ButtonGroup userSortGroup;
    // End of variables declaration//GEN-END:variables
}
